// Contenu du dossier « Veille & Montage » : Montage approfondi (iPhone compris),
// puis deux concepts tirés des meilleurs sites de la veille.
import { CONCEPTS as OLD } from './dossier4-content.mjs';

export const META = {
  serie: 'Troisième série, seconde édition — veille, Montage approfondi, deux nouvelles pistes',
  titre: 'Ce que font les meilleurs, et trois sites construits dessus<span class="dot">.</span>',
  lede: 'La veille reste la base : quatre corpus, environ 150 sites, les conventions, les gestes rares et les trous. Le concept retenu, Montage, est développé en profondeur : six écrans bureau, six écrans iPhone, l\'anatomie du téléphone, Safari, la technique. Deux nouvelles pistes le rejoignent, tirées directement des meilleurs sites vus : Plan-séquence et Repérage.',
  date: new Date().toLocaleDateString('fr-FR', { month: 'long', year: 'numeric' }),
  chiffres: [['4', 'corpus de veille'], ['≈ 150', 'sites visités'], ['88', 'fiches détaillées'], ['1', 'concept approfondi'], ['2', 'nouvelles pistes'], ['26', 'écrans maquettés']],
  changement: 'Sur la première édition, **Montage** a été retenu ; **Le point** et **Découpage** sont écartés. Montage gagne neuf pages, dont trois pour l\'iPhone. Les deux nouvelles pistes ne partent pas d\'une invention : chacune prolonge un geste vu chez les meilleurs (KAI, Önnu Jónu Son, Iconoclast, Ian Coad pour l\'une ; Bloom, Ligthelm pour l\'autre) et le pousse là où personne n\'est allé.',
  limites: 'Les captures de référence sont prises par un robot, à froid ; les sites qui ne vivent qu\'au mouvement apparaissent vides et sont écartés. Les maquettes sont des pages HTML réelles, dans la charte, avec vos images, sans vidéo : le mouvement y est simulé. Les lieux de tournage utilisés dans Repérage sont une hypothèse à confirmer avec vous.',
};

const M = OLD[0];
const montage = {
  ...M,
  deep: true,
  etats: [
    'Arrivée : trois plans posés, un quatrième en vol entre le chutier et la timeline ; la visionneuse joue le plan courant ; « Rythme lent · plans longs ».',
    'Le visiteur prend la main : un plan en cours de glisser, marqueur d\'insertion terracotta, poignées de rognage, filtre Tourisme actif.',
    'Films : le chutier complet, six bandes de quatre photogrammes ; « The Sound of Discovery » ouvert, approche, « Ajouter ces rushes ».',
    'Contact : le montage du visiteur en bande, le formulaire court, la pièce jointe EDL lisible, « Envoyer avec ma demande ».',
    'Studio : la timeline devient porte-notes ; les trois partis pris en marqueurs terracotta, le portrait dans la visionneuse.',
    'Rythme nerveux : le visiteur a bougé vite ; huit à dix plans courts serrés, coupes franches. À comparer avec l\'écran 01.',
  ],
  ecrans2Txt: [
    ['Le Studio sans page « à propos »', 'Le fondateur n\'a pas de page : il a des notes de montage. Ses trois partis pris sont posés en marqueurs sur la timeline, comme un monteur annote une séquence ; en ouvrir un affiche la note et son portrait dans la visionneuse. Le site reste une table, et l\'auteur apparaît dans son outil.'],
    ['Le rythme, la seule chose qu\'on n\'explique pas', 'Entre l\'écran 01 et l\'écran 06, rien n\'a été cliqué : le visiteur a seulement bougé plus vite. Le site a resserré ses coupes. On ne l\'écrit nulle part ; on le sent, et c\'est ce dont on parle après.'],
  ],
  mobile: [
    'Arrivée : visionneuse, cartouche, chutier en bande, timeline au pouce.',
    'Rythme : défilement rapide, timeline plus dense, mention du rythme.',
    'Appui long sur un rush : feuille « Ajouter au montage ».',
    'Édition : un plan soulevé, zones de dépôt, barre « Retirer · Rogner · Déplacer ».',
    'Films : les six bandes, un film déplié, « Ajouter ces rushes ».',
    'Contact : bande du montage, formulaire, pièce jointe repliée.',
  ],
  mobileLede: 'Le téléphone n\'est pas une réduction du bureau : c\'est l\'endroit où un client monte 40 secondes d\'immobilier en réunion et les envoie. Tout ce qui se fait au survol ou au glisser sur bureau a un équivalent au pouce : le tap, l\'appui long, et le glisser réservé à la timeline.',
  anatomie: [
    { state: 0, cap: 'Écran 01 — la table au repos', callouts: [
      { x: 50, y: 24, t: '**La visionneuse**, 16:9, toujours en haut ; le timecode et « Lecture » en incrustation.' },
      { x: 22, y: 40, t: '**Le cartouche** : film, client, catégorie, année, plan courant ; le rythme en dessous.' },
      { x: 50, y: 62, t: '**Le chutier** en bande horizontale défilable, filtres métier en chips au-dessus.' },
      { x: 30, y: 93, t: '**La timeline**, fixée au pouce, au-dessus de la barre d\'accueil ; tête de lecture terracotta.' },
    ] },
    { state: 3, cap: 'Écran 04 — édition de la timeline', callouts: [
      { x: 62, y: 83, t: '**Barre contextuelle** : Retirer · Rogner · Déplacer, cibles de 44 px.' },
      { x: 30, y: 94, t: '**Le plan soulevé** : ombre, échelle 1,04, zones de dépôt entre les plans.' },
      { x: 52, y: 94, t: '**Poignées de rognage** larges ; la visionneuse saute au point rogné.' },
    ] },
  ],
  gestesMobile: [
    ['Défiler (vertical)', 'Fait défiler la page normalement, et règle le rythme : vite = coupes serrées, lent = plans longs.'],
    ['Glisser la bande du chutier', 'Parcourt les rushes ; le filtre métier réduit la bande.'],
    ['Tap sur un rush', 'Aperçu dans la visionneuse (remplace le survol du bureau).'],
    ['Appui long sur un rush', 'Feuille « Ajouter au montage » : vignette, durée, « Tout le film », « Annuler ». Pas de menu natif.'],
    ['Tap sur un plan de la timeline', 'Le sélectionne ; barre « Retirer · Rogner · Déplacer ».'],
    ['Glisser sur la timeline seulement', 'Déplace le plan ou tire une poignée ; le défilement de la page est bloqué pendant le geste.'],
    ['Tap « Pause »', 'Arrête le montage automatique ; il ne reprend pas tout seul.'],
    ['Envoyer', 'Le montage part avec le message, avec un lien pour le rejouer.'],
  ],
  iphone: [
    { lbl: 'Safari et iOS', items: [
      'Hauteurs en `100svh`, jamais `100vh` : la barre d\'adresse de Safari change la hauteur visible.',
      'La timeline est en `position: fixed` avec `padding-bottom: env(safe-area-inset-bottom)` : au-dessus de la barre d\'accueil, jamais dessous.',
      'Le rebond élastique (`overscroll-behavior: none` sur le document) est coupé pour que le glisser sur la timeline ne tire pas la page.',
      '`-webkit-touch-callout: none` et `user-select: none` sur les rushes : l\'appui long ouvre notre feuille, pas le menu natif d\'iOS.',
      'Vidéo : `playsinline`, `muted`, `autoplay` ; iOS n\'autorise le son qu\'après un geste. Un bouton « Son » apparaît dans la visionneuse.',
    ] },
    { lbl: 'Performance', items: [
      'Affiches AVIF d\'abord, extraits vidéo ensuite et seulement pour les plans sur la timeline ; jamais plus de deux vidéos décodées à la fois.',
      'Le « vol » des plans est une animation FLIP sur `transform` : aucun calcul de mise en page pendant le geste.',
      'Le rythme lit la vitesse de défilement (Lenis expose la vélocité), lissée sur deux secondes ; rien n\'est envoyé au serveur.',
      'Cible : premier plan visible en moins de 1,8 s en 4G, aucun décalage de mise en page (ratios fixés).',
      'Mode économie d\'énergie ou `prefers-reduced-motion` : plus de vol, plus de fondu, coupes franches et montage automatique arrêté.',
    ] },
    { lbl: 'Ce qui change par rapport au bureau', items: [
      'Pas de glisser-déposer du chutier vers la timeline : l\'appui long puis la feuille le remplacent.',
      'La visionneuse reste en haut, la timeline en bas : le chutier et les fiches vivent entre les deux, en défilement.',
      'Le formulaire de contact ne recouvre pas la bande du montage : elle reste visible au-dessus du clavier.',
      'Le filtre métier est en chips défilables, pas en ligne : quatre visibles, la cinquième se devine.',
      'Le Studio n\'a pas de marqueurs cliquables au doigt : les notes sont listées sous la visionneuse.',
    ] },
  ],
  iphoneBas: 'Ce qui se vérifie sur un vrai iPhone avant toute mise en ligne : l\'appui long sur trois modèles (SE, 13, 15 Pro), le glisser sur la timeline sans que la page bouge, la visionneuse quand le clavier est ouvert, et le rythme au pouce. Chromium ne remplace pas Safari : ces quatre points sont testés à la main.',
  mesure: 'Trois événements suffisent : « le visiteur a pris la main », « nombre de plans à l\'envoi », « durée du montage à l\'envoi ». Si le troisième existe, le concept convertit.',
  chiffres: [['6-8 sem.', 'fabrication'], ['≈ 25', 'plans à préparer'], ['0', 'WebGL requis']],
};

export const CONCEPTS = [
  montage,
  {
    id: 'f4', num: '02', nom: 'Plan-séquence', famille: 'Le showreel est le site',
    phrase: 'Un film de quatre-vingt-dix secondes, et rien d\'autre. On ne navigue pas : on scrubbe.',
    pitch: 'Le site est un seul film continu monté à partir de vos meilleurs plans. Au repos il joue, sans interface. Dès que le pointeur bouge, un scrubber apparaît avec les scènes et les chapitres ; défiler ou glisser fait avancer et reculer le film. Chaque projet est une plage de timecode, **l\'URL porte le timecode**, et un filtre par métier **re-coupe le film** pour ne jouer que ce qui concerne le visiteur.',
    pitchCourt: 'Un seul film continu ; on le scrubbe au lieu de naviguer ; chaque projet est une plage de timecode et le filtre métier re-coupe le film.',
    dit: 'Un réalisateur qui ne montre que du film, jamais de brochure. Le plus radical des trois : le site est une œuvre, pas un catalogue.',
    rare: 'Le scrub au glisser existe (KAI), le scrubber à vignettes existe (Önnu Jónu Son), la séquence numérotée existe (Iconoclast), l\'explorateur de temps forts existe (Ian Coad). Personne ne les a réunis en faisant du film entier le site, avec un timecode dans l\'URL et un film qui se re-coupe par métier.',
    etats: [
      'Au repos : le film joue plein cadre, aucune interface sauf le logotype et un timecode minuscule.',
      'Le pointeur a bougé : scrubber avec vignettes de scènes et chapitres groupés par métier, tête de lecture terracotta, sous-titre du film courant.',
      'Fiche ouverte : le panneau crème glisse sur le film en pause (approche, photogrammes, client, année, « Reprendre le film »).',
      'FIN : le générique de fin est la carte contact, avec les cinq métiers et « Revoir ».',
    ],
    principe: [
      'Les maisons de production mettent un showreel en haut d\'une page. Ici, il n\'y a pas de page : le showreel est le site. Un film maître de quatre-vingt-dix secondes, monté à partir de vos meilleurs plans, occupe tout l\'écran et joue dès l\'arrivée, sans interface.',
      'Le premier mouvement du pointeur fait apparaître l\'instrument : en bas, un scrubber avec les vignettes de scènes et les chapitres, un par film, avec leurs timecodes, groupés par métier. Défiler ou glisser horizontalement fait avancer ou reculer le film, comme un monteur fait du jog ; relâcher, il reprend. Le titre du film courant et son client apparaissent en sous-titre au bon moment, puis s\'effacent.',
      'Chaque projet est une plage de timecode et l\'URL la porte : un lien envoyé à un client ouvre le site exactement sur le plan voulu. Cliquer sur l\'image ouvre la fiche du film sur un panneau de papier crème, le seul moment de charte imprimée : approche, photogrammes, client, année. Le film attend derrière, en pause.',
      'Les filtres par métier ne trient pas une liste : ils re-coupent le film. « Immobilier » fait jouer seulement les plages immobilières, en sautant le reste. Le site se remonte pour le visiteur, sans qu\'il quitte l\'image. À la fin, « FIN », puis le générique : c\'est la carte contact, écrite comme des crédits.',
    ],
    parcours: [
      'Il arrive : un film joue, plein cadre. Il ne cherche pas de menu ; il regarde.',
      'Il bouge la souris : le scrubber apparaît, il voit six chapitres. Il comprend que le film est le site.',
      'Il glisse vers la droite : le film avance, le sous-titre change de film. Il relâche : ça reprend.',
      'Il clique sur un plan qui l\'intéresse : la fiche crème, l\'approche, les photogrammes. « Reprendre ».',
      'Il choisit « Tourisme » : le film saute au premier plan tourisme, ne joue plus que ceux-là.',
      'Le film finit : le générique, l\'adresse, le téléphone. Il copie le lien : il rouvrira au même timecode.',
    ],
    veille: [
      'KAI : scrub fluide au glisser grâce à un encodage à images-clés courtes et un repli WebCodecs ; c\'est la brique de base.',
      'Önnu Jónu Son : scrubber à vignettes de scènes et interface invisible jusqu\'au mouvement ; on reprend les deux tels quels.',
      'Iconoclast : dix films numérotés en séquence sur l\'accueil, rien d\'autre ; six films en séquence paraissent un programme.',
      'Ian Coad : l\'explorateur de temps forts d\'un reel ; on va plus loin, le reel est tout le site. Emilie Aubry : l\'aperçu collé sur téléphone.',
    ],
    archiLede: 'Un film, six chapitres, un générique. Chaque chapitre est aussi une URL classique (/films/gone-colors) rendue en HTML avec son texte et ses photogrammes : les robots et les liens y accèdent sans jouer le film.',
    archi: [
      { k: '00:00', h: 'Le film', d: 'Quatre-vingt-dix secondes, plein cadre, muet par défaut, un bouton « Son ». Il joue dès l\'arrivée.' },
      { k: 'Chapitres', h: 'Six films', d: 'Une plage de timecode chacun, groupés par métier dans le scrubber ; l\'URL porte le timecode courant.' },
      { k: 'Clic', h: 'La fiche', d: 'Panneau crème : approche, quatre photogrammes, client, catégorie, année. Le film attend derrière.' },
      { k: 'Filtre', h: 'La re-coupe', d: 'Un métier = une liste de plages ; le film ne joue que celles-là et saute le reste.' },
      { k: 'FIN', h: 'Le générique', d: 'La carte contact écrite comme des crédits : adresse, mail, téléphone, métiers, réseaux, « Revoir ».' },
    ],
    gestes: [
      ['Ne rien faire', 'Le film joue ; l\'interface disparaît après deux secondes sans mouvement.'],
      ['Bouger le pointeur', 'Scrubber, chapitres, sous-titre ; le curseur devient « ◂ glisser ▸ ».'],
      ['Glisser horizontalement / molette', 'Scrub : le film avance ou recule à la vitesse du geste ; relâcher, il reprend.'],
      ['Cliquer un chapitre', 'Saute au début de sa plage ; l\'URL change.'],
      ['Cliquer l\'image', 'Ouvre la fiche du film courant ; le film se met en pause, s\'assombrit.'],
      ['Choisir un métier', 'Re-coupe : seules les plages du métier jouent ; « Tout le film » pour revenir.'],
      ['← / →, Espace', 'Scrub image par image, lecture / pause : les raccourcis d\'un logiciel de montage.'],
    ],
    motion: [
      'Le film est le mouvement ; l\'interface n\'a droit qu\'à des fondus de 250 ms et à la tête de lecture.',
      'Le scrub n\'a pas d\'inertie artificielle : la vitesse du geste est la vitesse du film, puis il reprend à 1×.',
      'Le sous-titre apparaît au changement de chapitre et s\'efface après trois secondes.',
      'La fiche glisse depuis la droite en 500 ms ; derrière, le film s\'assombrit à 35 %.',
      'Le générique monte lentement, comme au cinéma ; « Revoir » remet au début.',
    ],
    mobile: ['Le film plein écran, scrubber vertical fin à droite.', 'Après défilement : sous-titre, bande de chapitres, chips métier.', 'Fiche en feuille qui monte du bas.'],
    mobileTxt: 'Le défilement vertical scrubbe le film : c\'est le geste le plus naturel du téléphone, et il devient un jog. Le scrubber est un trait fin à droite ; la bande de chapitres apparaît en bas après le premier geste ; le tap ouvre la fiche en feuille. Version mobile du film : vingt secondes par métier, plus légère, ou une séquence d\'images sur connexion lente.',
    tech: [
      'Film maître encodé en plusieurs débits (H.264 et AV1), images-clés toutes les 12 images, `faststart` ; version mobile courte.',
      'Scrub par `currentTime` sur le flux à images-clés courtes ; repli WebCodecs (mediabunny) pour Firefox, comme chez KAI.',
      'Le timecode dans l\'URL (`#tc=`) ; les chapitres sont des routes HTML complètes avec texte et photogrammes, pour le référencement.',
      'La re-coupe par métier est une liste de plages ; la lecture saute d\'une plage à l\'autre sans recharger.',
      'Muet par défaut, bouton « Son » ; iOS : `playsinline`, autoplay muet, scrub tactile sur l\'axe vertical.',
      'Clavier : ← / → scrub, Espace lecture, Tab sur les chapitres (liste de liens) ; `prefers-reduced-motion` : le film ne joue pas seul, on scrubbe.',
      'Poids : 90 s à 1080p ≈ 12 Mo en AV1, servis par plages ; l\'affiche du premier plan en moins d\'une seconde.',
    ],
    besoin: 'Un film maître de 90 secondes monté par vous, avec un EDL des plages par film et par métier ; une version de 20 secondes par métier pour le téléphone.',
    risques: 'Le visiteur qui veut « juste la liste » : parade, les chapitres sont une liste de liens dès le premier mouvement, et chaque film a sa page. Le poids : parade, débits adaptatifs et version courte sur mobile. Les navigateurs sans scrub fluide : parade WebCodecs.',
    chiffres: [['5-7 sem.', 'fabrication'], ['90 s', 'de film maître'], ['6', 'chapitres']],
  },
  {
    id: 'f5', num: '03', nom: 'Repérage', famille: 'Le territoire et la lumière',
    phrase: 'Bordeaux est notre plateau. Une carte à l\'encre, une molette de lumière, et un site qui n\'est jamais le même à 7 h et à 22 h.',
    pitch: 'Le site est un dossier de repérage : une carte de la Gironde dessinée au trait, vos lieux de tournage épinglés en photogrammes, et une molette de lumière (aube, midi, heure dorée, nuit) qui **ré-étalonne tout le site** et fait remonter les plans tournés à cette lumière. Par défaut, elle est réglée sur l\'heure réelle à Bordeaux. Le contact est « votre repérage » : un lieu, une heure, un métier.',
    pitchCourt: 'Une carte de la Gironde à l\'encre, les lieux tournés épinglés, une molette de lumière qui ré-étalonne le site ; le contact est un repérage.',
    dit: 'Un réalisateur d\'ici, qui connaît la lumière et les décors. Le plus ancré des trois, et le seul qui parle directement aux clients tourisme, immobilier et événementiel.',
    rare: 'Bloom vend des lieux plutôt que des services, Ligthelm affiche GPS et pellicule. Personne ne fait du territoire la structure du site, ni ne relie le site à l\'heure réelle. C\'est le trou n° 1 des corpus « réalisateurs » et « Bordeaux ».',
    etats: [
      'Arrivée : la carte à l\'encre, six épingles-photogrammes, l\'encart « Hors champ », la molette sur « heure dorée ».',
      'La molette tournée sur « nuit » : tout le site ré-étalonné, papier sombre chaud ; les plans de nuit remontent, les autres s\'estompent.',
      'Fiche de repérage « Médoc » : photogrammes, lumière, saison, notes d\'accès, film concerné, « Ajouter à mon repérage ».',
      '« Votre repérage » : l\'épingle du client, l\'heure choisie, le métier, le formulaire court, « Envoyer le repérage ».',
    ],
    principe: [
      'Avant de tourner, un réalisateur repère : le lieu, l\'heure, la lumière, l\'accès. Le site rend ce travail visible et en fait sa structure. La page d\'accueil est une carte de la Gironde dessinée au trait d\'encre sur papier crème : l\'estuaire, la Garonne, le Bassin, le littoral, le Médoc. Ce n\'est pas une carte routière ; c\'est un dessin de repérage.',
      'Les lieux où vous avez tourné sont épinglés comme de petits photogrammes. Les deux films tournés ailleurs vivent dans un encart « Hors champ » au bord de la carte. Choisir un lieu ouvre sa fiche de repérage : les plans tournés là, la lumière, la saison, vos notes d\'accès, le film. Choisir un métier surligne les lieux où il a été tourné.',
      'À droite, une molette de lumière : aube, matin, midi, heure dorée, crépuscule, nuit. La tourner ré-étalonne tout le site, le papier, les images, les ombres, et fait remonter les photogrammes tournés à cette lumière. Par défaut, elle est réglée sur l\'heure réelle à Bordeaux, lever et coucher calculés : le site n\'est jamais le même à 7 h et à 22 h, et personne ne fait cela.',
      'Le contact est un repérage : le client pose une épingle (un lieu, ou « à définir »), choisit une heure et un métier, écrit trois lignes. Vous recevez un brief qui dit déjà où, quand, et dans quelle lumière.',
    ],
    parcours: [
      'Il arrive à 18 h 40 : la carte est ambrée, heure dorée. Il voit Bordeaux, le Médoc, le Bassin, des photogrammes épinglés.',
      'Il tourne la molette vers la nuit : le papier s\'assombrit, le concert et le feu d\'artifice de La Médocaine remontent.',
      'Il clique sur le Médoc : la fiche, les plans, les notes d\'accès. Il comprend que vous connaissez le terrain.',
      'Il choisit « Immobilier » : les lieux où vous l\'avez tourné se surlignent.',
      'Il ouvre « Votre repérage », pose une épingle sur le Bassin, choisit l\'aube, écrit trois lignes, envoie.',
      'Vous recevez : Bassin d\'Arcachon, aube, immobilier, et son message.',
    ],
    veille: [
      'Bloom : « Down South / West coast / Alps », vendre des lieux plutôt que des services ; on le pousse jusqu\'à la carte.',
      'Ligthelm : GPS, lieu et pellicule comme métadonnées de film ; ici la métadonnée devient la navigation.',
      'Neels Castillon : la voie claire sur crème ; SOMA et Brady Perron : la variabilité (aléatoire, idle states) est acceptée par le public, on la relie au réel.',
      'Trou n° 1 des corpus « réalisateurs » et « Bordeaux » : personne n\'ancre un territoire autrement qu\'en liste de communes pour le référencement.',
    ],
    archiLede: 'Une carte, des lieux, une molette. Chaque lieu et chaque film est une page HTML complète (/lieux/medoc, /films/la-medocaine) : c\'est aussi le concept le plus fort pour le référencement local, « vidéaste Médoc », « film Bassin d\'Arcachon », sans page pilier artificielle.',
    archi: [
      { k: 'Carte', h: 'Les lieux', d: 'La Gironde à l\'encre, les lieux tournés épinglés en photogrammes, l\'encart « Hors champ » pour l\'ailleurs.' },
      { k: 'Molette', h: 'La lumière', d: 'Six heures ; ré-étalonne tout le site et filtre les plans par lumière. Réglée sur l\'heure réelle par défaut.' },
      { k: 'Lieu', h: 'La fiche de repérage', d: 'Plans, lumière, saison, notes d\'accès du réalisateur, films concernés, « Ajouter à mon repérage ».' },
      { k: 'Métier', h: 'Le surlignage', d: 'Corporate, événementiel, immobilier, tourisme, clip : les lieux où chacun a été tourné.' },
      { k: 'Contact', h: 'Votre repérage', d: 'Une épingle, une heure, un métier, trois lignes ; le brief part avec le lieu et la lumière voulue.' },
    ],
    gestes: [
      ['Arriver', 'La molette se règle sur l\'heure réelle à Bordeaux ; la carte est étalonnée en conséquence.'],
      ['Tourner la molette', 'Le site change de lumière en 900 ms ; les plans de cette lumière remontent, les autres s\'estompent.'],
      ['Survoler une épingle', 'Le photogramme s\'agrandit, le nom du lieu et le film s\'affichent.'],
      ['Cliquer un lieu', 'La fiche de repérage glisse à droite ; la carte zoome légèrement sur le lieu.'],
      ['Choisir un métier', 'Surligne les lieux concernés ; les autres passent en trait pâle.'],
      ['Glisser la carte', 'Panoramique ; molette de la souris = zoom ; double-clic = recentrer.'],
      ['Poser une épingle', 'Dans « Votre repérage » : un lieu ou « à définir », puis heure et métier.'],
    ],
    motion: [
      'L\'étalonnage : température du papier, teinte des images et longueur des ombres changent ensemble, en 900 ms, courbe douce.',
      'Les épingles respirent à peine au repos ; celles de la lumière courante sont nettes, les autres pâlissent.',
      'La carte ne bouge que sous la main ; le zoom sur un lieu est court (500 ms) et revient au même rythme.',
      'La fiche glisse sur le papier comme une feuille posée, avec une ombre très légère.',
      'De nuit, l\'encre devient crème ; c\'est la seule fois où le site est sombre, et c\'est l\'heure qui décide.',
    ],
    mobile: ['La carte plein écran, la molette en arc au pouce.', 'Fiche de repérage en feuille, photogrammes défilables.', '« Votre repérage » : heure, lieu, métier, envoi.'],
    mobileTxt: 'La molette devient un arc sous le pouce, en bas ; la carte se déplace au doigt sans voler le défilement (un geste à un doigt sur la carte, deux doigts pour zoomer). Les fiches montent en feuilles. Le contact tient sur un écran : une épingle, une heure, un métier, trois lignes.',
    tech: [
      'Carte en SVG statique dessiné une fois (formes simplifiées de la Gironde), lieux et films en données structurées (JSON ou CMS léger).',
      'Lever et coucher calculés côté client pour Bordeaux (latitude fixe) ; la molette suit l\'heure réelle jusqu\'au premier geste.',
      'Étalonnage par variables CSS et filtres sur les images ; aucune dépendance WebGL ; six états de lumière pré-définis.',
      'Pages lieu et pages film rendues en HTML complet : référencement local naturel, données structurées Place et VideoObject.',
      'La molette est un `input type=range` avec étiquettes ; clavier : flèches ; `prefers-reduced-motion` : changement instantané.',
      'Mobile : pan de la carte par pointer events avec `touch-action: none` sur la carte seule ; le reste défile normalement.',
      'Poids : la carte ≈ 40 Ko, les photogrammes à la demande ; le site le plus léger des trois après l\'accueil.',
    ],
    besoin: 'Les lieux réels de chaque film (ceux de la maquette sont une hypothèse), deux ou trois lignes de notes d\'accès par lieu, et l\'heure de tournage des plans clés. Une séance suffit.',
    risques: 'Une carte avec six épingles paraît vide : parade, les plans épinglés sont grands et l\'encart « Hors champ » et le studio comptent ; chaque nouveau film enrichit la carte. La nuit sombre peut surprendre : parade, elle ne s\'impose qu\'aux heures de nuit et se change d\'un geste.',
    chiffres: [['5-7 sem.', 'fabrication'], ['6', 'heures de lumière'], ['0', 'WebGL requis']],
  },
];

export const RECO = {
  titre: 'Montage, et deux compagnons possibles<span class="dot">.</span>',
  grille: [
    ['Effet « je n\'ai jamais vu ça »', 5, 4, 4],
    ['Geste de réalisateur', 4, 5, 4],
    ['Utile au client (brief, devis)', 5, 3, 5],
    ['Lecture en 30 s sur téléphone', 4, 4, 4],
    ['Indexable, crédible à Bordeaux', 3, 3, 5],
    ['Légèreté de fabrication', 3, 3, 4],
    ['Robustesse (vieillit bien)', 4, 3, 5],
  ],
  legende: 'Cinq carrés = le plus fort. Les notes sont un avis, pas une mesure : elles croisent la veille (ce qui est rare, ce qui vieillit mal) et ce que vos clients corporate, immobilier et tourisme attendent.',
  avis: [
    '**Montage** reste le cœur : c\'est le seul concept où le visiteur repart avec quelque chose qu\'il a fait, et où vous recevez un brief déjà filmé. Les trois pages iPhone montrent qu\'il tient au pouce, à condition de remplacer le glisser par l\'appui long.',
    '**Plan-séquence** est le plus radical et le plus « cinéma » : un film, rien d\'autre. Il vient directement des meilleurs sites vus (KAI, Önnu Jónu Son, Iconoclast) et les dépasse par le timecode dans l\'URL et la re-coupe par métier. Il demande un vrai film maître monté par vous.',
    '**Repérage** est le plus ancré et le plus vendeur pour vos clients : le territoire, la lumière, l\'heure réelle. Il gagne le référencement local sans page pilier, et c\'est celui qui parle le mieux à un promoteur, un office de tourisme ou un domaine.',
  ],
  combine: 'Montage et Repérage se combinent naturellement : le chutier de Montage peut se filtrer par lieu et par lumière, et « Votre repérage » devient la seconde moitié du brief (le montage dit le rythme, le repérage dit le lieu et l\'heure). Plan-séquence est l\'autre voie : plus pure, moins outillée. Mon assemblage préféré : **Montage + Repérage**.',
  suiteTitre: 'Comment on avance<span class="dot">.</span>',
  etapes: [
    { h: 'Choisir', d: 'Montage seul, ou Montage + Repérage, ou Plan-séquence. Dites ce qui vous a fait réagir dans les écrans, en bien comme en mal.' },
    { h: 'Préparer la matière', d: 'Montage : 25 plans courts tagués par métier, lieu et lumière. Repérage : les lieux réels et deux lignes de notes par lieu. Plan-séquence : le film maître de 90 s.' },
    { h: 'Construire', d: 'Version Next.js sur une branche, déployée en aperçu, testée sur iPhone réel et sur Safari. Le site actuel reste en ligne jusqu\'au dernier jour.' },
  ],
};
