// Contenu du dossier « Veille & concepts ». Tout ce qui est factuel sur les
// sites vient des synthèses de veille (scratchpad/veille/synthese-*.md).

export const META = {
  serie: 'Troisième série — veille et concepts',
  titre: 'Ce que font les meilleurs, ce que personne ne fait, et trois sites qui n\'existent pas encore<span class="dot">.</span>',
  lede: 'Quatre agents ont écumé les sites de maisons de production, de réalisateurs, de studios parisiens et de vidéastes bordelais, puis les études de cas techniques des sites les plus primés. Ce dossier en tire des règles, des trous, et trois concepts complets : l\'idée, l\'architecture, chaque écran, le téléphone, la technique.',
  date: new Date().toLocaleDateString('fr-FR', { month: 'long', year: 'numeric' }),
  chiffres: [['4', 'corpus de veille'], ['≈ 150', 'sites visités'], ['88', 'fiches détaillées'], ['33', 'mécaniques cataloguées'], ['3', 'concepts développés'], ['21', 'écrans maquettés']],
  changement: 'Les deux séries précédentes proposaient des directions visuelles. Celle-ci part de l\'observation : ce que les sites de référence font vraiment (et ce qu\'ils ne font jamais), puis construit trois sites autour d\'un **geste de réalisateur** que personne n\'a encore mis en ligne. Chaque concept est expliqué de bout en bout, pas seulement montré.',
  limites: 'Les captures de référence sont prises par un robot, à froid, sans survol : les sites qui ne vivent qu\'au mouvement (Nabil, Hiro Murai, Groshev) apparaissent vides et sont écartés. Les maquettes des concepts sont des pages HTML réelles, dans la charte, avec vos images, mais sans vidéo : le mouvement y est simulé. Rien n\'est encore branché sur le site en ligne.',
};

export const VEILLE = {
  titre: 'Quatre corpus, une question : à quoi ressemble un site de réalisateur en 2026, et où est la place libre<span class="dot">.</span>',
  lede: 'Chaque agent a visité les sites, lu le code quand la page était vide, et noté pour chacun l\'accueil, la navigation, ce qui est rare et ce qui déçoit. Les synthèses tiennent en 140 000 caractères ; voici l\'essentiel.',
  corpus: [
    { n: '27', l: 'Maisons de production', d: 'Iconoclast, Division, Caviar, Partizan, Somesuch, Biscuit, Pulse, Prettybird, Smuggler, Stink, MJZ, Riff Raff, Reset, Directors Bureau, Park Pictures…' },
    { n: '25', l: 'Réalisateurs & chefs op', d: 'Salomon Ligthelm, Emilie Aubry, Josh Goldsmith, Ian Coad, Bradley & Pablo, Megaforce, Neels Castillon, Chris Macari, Brady Perron, SOMA, Tim Flower…' },
    { n: '36', l: 'Paris & Bordeaux', d: '16 maisons parisiennes (Iconoclast, La Pac, Badass, Wanda, Bloom, Control, Big, Division…) et 20 vidéastes ou agences bordelais (Sajot, Fygo, Manza, Biux, Peech, Storystellar…).' },
    { n: '33', l: 'Mécaniques techniques', d: 'Études de cas Codrops, Awwwards et FWA 2025-2026 : scrub vidéo, cartes de profondeur, datamosh, grilles à inertie, splats, curseur-torche, long press, son piloté par le scroll…' },
  ],
  methode: 'Méthode : recherche web puis lecture de chaque site (HTML et CSS inclus, quand l\'accueil est vide sans JavaScript), fiches normalisées **Accueil / Navigation / Rare / Faible**, puis synthèse par corpus. Les sites injoignables (Cloudflare, erreurs 5xx) sont listés et non commentés. Les captures de ce dossier viennent d\'un service de rendu externe, à 1440 × 900, après 3,5 s d\'attente.',
  planches: [
    {
      kicker: 'Corpus 1 — maisons de production internationales', titre: 'Le roster, la grille, le noir : la forme dominante', folio: 'Références I',
      note: 'Captures 1440 × 900, à froid',
      refs: [
        { key: 'icono', nom: 'Iconoclast', url: 'iconoclast.tv', cap: 'Carrousel de 10 films numérotés avec timeline, rien d\'autre sur l\'accueil. Sept pays en sélecteur.' },
        { key: 'division', nom: 'Division', url: 'division.global', cap: 'Grille de vidéos muettes, curseur à anneau de progression. Cinq sous-domaines par marché.' },
        { key: 'caviar', nom: 'Caviar', url: 'caviar.tv', cap: 'Le seul à quitter le noir et blanc : taupe, brun, serif d\'affichage. Nom en plein cadre.' },
        { key: 'somesuch', nom: 'Somesuch', url: 'somesuch.co', cap: 'Titres énormes, images N&B, panier et section « Editions » : la maison vend aussi des objets.' },
        { key: 'biscuit', nom: 'Biscuit Filmworks', url: 'biscuitfilmworks.com', cap: 'Le roster est la page d\'accueil : trois colonnes de noms sur une image. Rien à lire, tout à choisir.' },
        { key: 'pulse', nom: 'Pulse Films', url: 'pulsefilms.com', cap: 'Logotype comme masque de vidéo, nav à quatre mots aux angles. Le modèle « showreel sans chrome ».' },
        { key: 'prettybird', nom: 'Prettybird', url: 'prettybird.co', cap: 'Vidéo plein cadre, titre au centre, « Explore » en bas. Noir et blanc strict, typographie neutre.' },
        { key: 'directorsbureau', nom: 'The Directors Bureau', url: 'thedirectorsbureau.com', cap: 'Page-porte : la liste des noms d\'abord, « ENTER » tout en bas. La porte est la conclusion.' },
      ],
      bas: 'Douze conventions reviennent dans 27 sites : grille titre + réalisateur en accueil, film rangé sous son réalisateur dans l\'URL, roster en liste de noms nue, sélecteur de pays, vignettes vidéo muettes, nav de 3 à 5 mots, format « Marque – Titre by Réalisateur », palette noir/blanc, et des accueils vides sans JavaScript.',
    },
    {
      kicker: 'Corpus 2 — réalisateurs et chefs opérateurs', titre: 'L\'index, le hover, le preloader : le portfolio d\'auteur', folio: 'Références II',
      note: 'Sites vides à froid écartés : Nabil, Hiro Murai, Groshev',
      refs: [
        { key: 'ligthelm', nom: 'Salomon Ligthelm', url: 'ligthelm.work', cap: 'Archive en grille numérotée, GPS et pellicule en métadonnées, citations en « resting place » entre les films.' },
        { key: 'joshgoldsmith', nom: 'Josh Goldsmith', url: 'josh-goldsmith.com', cap: 'Cube 3D de showreel qu\'on attrape et qu\'on lance ; index dont le survol projette la vidéo en fond.' },
        { key: 'emilieaubry', nom: 'Emilie Aubry', url: 'emilieaubry.com', cap: 'Liste + aperçu vidéo qui suit le curseur, bascule liste/grille, « sticky preview » sur téléphone.' },
        { key: 'neels', nom: 'Neels Castillon', url: 'neelscastillon.com', cap: 'Grille d\'images sur fond crème, nav en serif : la rare voie claire, proche de votre charte.' },
        { key: 'bradleypablo', nom: 'Bradley & Pablo', url: 'bradleyandpablo.com', cap: 'Zéro image à l\'accueil : contacts routés par pays et par usage. La page info comme porte.' },
        { key: 'gsproductions', nom: 'GS Productions', url: 'gsproductions.co.za', cap: 'Fond clair, slider projet, bascule liste/grille, transitions Lenis. Le standard 2026 primé.' },
        { key: 'megaforce', nom: 'Megaforce', url: 'megaforce.fr', cap: 'Un index texte intégral sur fond métallisé, clips et pubs mêlés. Aucune vignette : le titre suffit.' },
        { key: 'soma', nom: 'SOMA', url: 'soma.ca', cap: 'Roster chargé dans un ordre aléatoire (« no main character »), manifeste qui tombe, nom en plein cadre.' },
      ],
      bas: 'Chez les réalisateurs : noir + un accent, preloader, index texte + vidéo au survol, bascule liste/grille, nav à deux ou trois mots, classement par format (Commercials / Music Videos / Narrative), fiche film = vidéo plein écran + crédits repliés + précédent/suivant, contacts par territoire sans formulaire, crédit du studio web en pied : le site est lui-même une pièce de portfolio.',
    },
    {
      kicker: 'Corpus 3 — Paris et Bordeaux', titre: 'Le silence parisien, le catalogue bordelais', folio: 'Références III',
      note: 'Concurrence directe en bas de planche',
      refs: [
        { key: 'lapac', nom: 'La Pac', url: 'pac.fr', cap: 'Paris. « My Collection » : le producteur d\'agence compose sa sélection de films pour son pitch.' },
        { key: 'badass', nom: 'Badass Films', url: 'badassfilms.tv', cap: 'Paris. Galerie vidéo avec sélecteur au scroll, typographie animée, bichromie. Site signé Ensemble.' },
        { key: 'bloomparis', nom: 'Bloom', url: 'bloomparis.tv', cap: 'Paris. Vend des lieux plutôt que des services : « Down South, West coast, Alps ». Compteur « /35 work ».' },
        { key: 'reset', nom: 'Reset', url: 'resetcontent.com', cap: 'Le menu est le roster ; organigramme avec emails directs par région. Transparence maximale du corpus.' },
        { key: 'sajot', nom: 'Lucas Sajot', url: 'lucassajot.com', cap: 'Bordeaux. Concurrent direct n° 1 : même cible, même promesse d\'auteur, 4,9/46 avis, Frame.io — WordPress sans film à l\'accueil.' },
        { key: 'fygo', nom: 'Fygo', url: 'fygostudio.com', cap: 'Bordeaux. WordPress soigné, GIF en guise de portfolio, menu par prestation.' },
        { key: 'manza', nom: 'Manza Studio', url: 'manza-studio.com', cap: 'Bordeaux. Le seul local décrit comme sur-mesure (Webflow). 54 avis Google.' },
        { key: 'biuxbdx', nom: 'Biux — page Bordeaux', url: 'biux.fr', cap: 'Agence nationale : page locale dupliquée, fourchettes de prix 3 000 à 12 000 € HT. Tient le SEO « agence vidéo Bordeaux » sans tourner ici.' },
      ],
      bas: 'À Paris : roster, silence textuel, vidéo plein cadre, nav de trois mots, sites signés Ensemble ou Beaucoup. À Bordeaux : WordPress à thème (80 %), menu-catalogue de 7 à 11 prestations, page pilier SEO avec liste de communes, avis Google et compteurs, process en 4 étapes, FAQ « combien ça coûte : ça dépend », et **aucune vidéo sur l\'accueil dans 12 sites sur 20**.',
    },
    {
      kicker: 'Corpus 4 — sites expérimentaux et études de cas techniques', titre: 'Ce que le navigateur sait faire avec de la vidéo en 2026', folio: 'Références IV',
      note: 'Codrops, Awwwards, FWA — 2025-2026',
      refs: [
        { key: 'kai', nom: 'KAI', url: 'kai-group.com', cap: 'Scrub vidéo au glisser, encodage à images-clés courtes (-g 12) et repli WebCodecs : le geste de jog fluide.' },
        { key: 'risk', nom: 'RISK', url: 'risk.film', cap: 'Primé Awwwards : créativité 7,43, usabilité 6,82. Le cas d\'école de la prouesse qui coûte l\'usage.' },
        { key: 'phantom', nom: 'Phantom', url: 'phantom.land', cap: 'Grille draggable à inertie, dézoom au glisser, portrait + carte de profondeur → particules 3D.' },
        { key: 'scan', nom: 'Scan Effect (Codrops)', url: 'tympanus.net', cap: 'Carte de profondeur → parallaxe et balayage WebGPU : l\'image plate retrouve sa distance.' },
        { key: 'fourwide', nom: '4WIDE', url: '4wide.jp', cap: 'Distorsion, flou et « focus mode » à vitesse 0,6 ; le flou est coupé sur mobile, « l\'ajustement le plus efficace ».' },
        { key: 'bisous', nom: 'Bisous', url: 'bisous-production.com', cap: 'Le contre-modèle : un site de production « cinématique » sans WebGL, éditorial et rapide.' },
        { key: 'chems', nom: 'Chems Studio', url: 'chems.studio', cap: '« Nothing loops simply for decoration » : archive flexible, transitions invisibles, lecteur intégré.' },
        { key: 'datamosh', nom: 'Datamosh (Codrops)', url: 'tympanus.net', cap: 'Le codec comme langage : la compression vidéo devient la transition entre deux films.' },
      ],
      bas: 'Pièges relevés : les sites de prouesse meurent (Skyline Films redirige vers un site de sport), le « desktop only » est assumé par certains (The Spark), les primés ont des scores d\'usabilité et d\'accessibilité bas (Igloo 6,6/10), le post-process plein écran ne passe pas sur téléphone, et le scrub exige un pipeline d\'encodage. Règle retenue : **un effet est un moment, pas une navigation** — sauf s\'il a un état « off » propre.',
    },
  ],
  pages: [
    {
      kicker: 'Synthèse — les conventions', titre: 'Ce qu\'on retrouve partout<span class="dot">.</span>', folio: 'Conventions', cols: 3,
      lede: 'Ces habitudes ne sont pas des erreurs : elles marchent. Mais elles décrivent des maisons à 20 ou 45 réalisateurs, ou des vidéastes qui vendent un catalogue. Aucune n\'a été pensée pour un auteur seul.',
      colonnes: [
        { lbl: 'Maisons de production', items: [
          '**La grille titre + réalisateur** comme accueil (Stink, Academy, Partizan, Rattling Stick, Landia, Caviar).',
          '**Le roster d\'abord** : « Directors » en première entrée, film rangé sous son réalisateur dans l\'URL.',
          '**Le sélecteur de pays** dans l\'en-tête, roster distinct par marché (Iconoclast 7, Division 5, Caviar 5).',
          '**Vignettes vidéo muettes** en autoplay (Riff Raff : 599 balises vidéo sur une page).',
          '**Noir et blanc** : Caviar écrit avoir abandonné la couleur pour ne pas concurrencer les films.',
          '**Accueil vide sans JavaScript** : Next, Nuxt, Webflow — score sémantique Awwwards de Bullion : 6,67/10.',
        ] },
        { lbl: 'Réalisateurs', items: [
          '**Noir + un accent** (Ligthelm gris, Macari rouge, SOMA orange, Naked City bleu).',
          '**Preloader à compteur** presque systématique sur les sites primés (« LOADING 0 % »).',
          '**Index texte + vidéo au survol**, aperçu qui suit le curseur (Aubry), fond miroir (Goldsmith).',
          '**Bascule liste / grille**, devenue un standard 2026 (Aubry, GSP, Perron).',
          '**Classement par format** : Commercials / Music Videos / Narrative. Jamais par client ni par secteur.',
          '**Contacts routés par territoire**, pas de formulaire (Ligthelm 6 régions, Bradley & Pablo par usage).',
        ] },
        { lbl: 'Bordeaux', items: [
          '**WordPress à thème** dans 80 % des cas ; trois Webflow ; un Squarespace avec panier oublié.',
          '**Menu par prestation** (7 à 11 entrées), mariage et corporate mélangés.',
          '**Page pilier SEO** « vidéaste Bordeaux » avec listes de communes (Xaleo : 16) et H2 en questions.',
          '**Preuves chiffrées** : avis Google (Sajot 4,9/46, Storystellar 195), compteurs « +200 projets », années d\'expérience.',
          '**Devis comme seul appel à l\'action**, « ça dépend » comme seule réponse tarifaire.',
          '**Le matériel comme argument** (8K RAW, drone DGAC, DaVinci certifié) — et pas de film sur l\'accueil.',
        ] },
      ],
    },
    {
      kicker: 'Synthèse — les gestes rares', titre: 'Ce qu\'on n\'a vu qu\'une fois<span class="dot">.</span>', folio: 'Gestes rares', cols: 3,
      lede: 'Une soixantaine de gestes rares ont été relevés et sourcés. Ceux-ci sont les plus pertinents pour un réalisateur seul : ils prouvent qu\'une idée est acceptée par le public, sans être encore un cliché.',
      colonnes: [
        { lbl: 'Navigation', items: [
          '**Le menu est le roster** : un bouton qui déroule directement les noms (Reset).',
          '**« ENTER » en bas de page**, après la liste : la porte est la conclusion (Directors Bureau).',
          '**« My Collection »** : le visiteur compose sa propre sélection de films (La Pac) — le seul précédent d\'un site qui laisse le visiteur assembler.',
          '**Reel highlight explorer** : naviguer dans les temps forts du showreel plutôt que le subir (Ian Coad).',
          '**Vendre des lieux plutôt que des services** : « Down South / West coast / Alps » (Bloom).',
          '**Carrousel de 10 films numérotés** et rien d\'autre (Iconoclast) : 10 films en séquence paraissent un programme, en grille ils paraîtraient maigres.',
        ] },
        { lbl: 'Matière et rendu', items: [
          '**Cube 3D de showreel** qu\'on attrape et qu\'on lance ; overscroll « pixel wash » (Josh Goldsmith).',
          '**État REC** qui fait virer tout le site au rouge (Chris Macari, lu dans le CSS).',
          '**GPS, lieu et pellicule** comme métadonnées de film (Ligthelm).',
          '**Scrubber à vignettes de scènes**, interface invisible jusqu\'au mouvement (Önnu Jónu Son).',
          '**Long press qui révèle la vidéo** derrière l\'image fixe (David Whyte, Immersive Garden).',
          '**Carte de profondeur** → parallaxe et flou dépendant de la distance (Scan Effect, Phantom).',
        ] },
        { lbl: 'Relation client', items: [
          '**Organigramme avec emails directs** par région (Reset) ; « Sales » en entrée de nav (MJZ).',
          '**Suivi Frame.io et « réponse sous 6 h »** affichés comme promesse (Lucas Sajot).',
          '**Fourchettes de prix par format** publiées (Biux : 3 000 à 12 000 € HT ; Gautier V : dès 450 € HT).',
          '**« Une journée d\'immobilisation, deux livrables »** : l\'argument est le temps du client (Studio Tonelli).',
          '**Trois études de cas seulement**, racontées, au lieu de cinquante vignettes (Letter to Memphis).',
          '**Consigne opérationnelle en pied** : « brief en PDF léger, pas de lien » (Ian Pons Jewell).',
        ] },
      ],
    },
    {
      kicker: 'Synthèse — les trous', titre: 'Ce que personne ne fait<span class="dot">.</span>', folio: 'La place libre', cols: 2, dark: true,
      lede: 'Croisement des quatre corpus. Chaque ligne est un vide réel dans 150 sites, et chacun est tenable par un réalisateur seul à Bordeaux. Les trois concepts qui suivent sont construits dessus.',
      colonnes: [
        { lbl: 'Dans la forme', items: [
          '**Aucun site n\'est construit autour d\'une seule personne.** Tous sont des rosters ; la fiche réalisateur est une page secondaire. L\'inverser, c\'est mettre au premier niveau ce que les maisons cachent au troisième.',
          '**Personne ne laisse le visiteur assembler.** La Pac a « My Collection », Ian Coad un explorateur de temps forts : personne ne va jusqu\'au montage par le visiteur. Le corpus technique le dit en toutes lettres : « territoire libre ».',
          '**Personne n\'utilise la mise au point comme navigation.** Les cartes de profondeur servent au décor (Phantom, Scan Effect), jamais à choisir. La bague de point reste libre.',
          '**Personne n\'écrit comme un réalisateur.** Ni découpage, ni note d\'intention, ni « je » : à Paris le silence, à Bordeaux la brochure. Le document de travail du réalisateur n\'a jamais été mis en ligne comme site.',
          '**Le curseur n\'est jamais un outil de lecture** hormis l\'anneau de Division et le play/pause de DVEIN : le scrub au pointeur est disponible.',
        ] },
        { lbl: 'Dans le fond', items: [
          '**Personne ne montre le processus ni le temps** : brief, repérage, jours de tournage, délai de livraison. Un seul indice dans 150 sites (l\'animatique comparée de Riff Raff).',
          '**Personne ne classe par usage client** : toujours Commercial / Music Video / Narrative, jamais « faire visiter un bien », « raconter un événement », « vendre une destination ».',
          '**Personne n\'ancre un territoire** autrement qu\'en liste de communes : ni Médoc, ni Bassin, ni Chartrons comme décors connus, films à l\'appui.',
          '**Personne ne donne de chiffres côté premium** : ni durée, ni délai, ni fourchette, ni taille d\'équipe. Le milieu bordelais (Sajot, Fygo, Manza) ne dit rien.',
          '**Personne ne joue le réel** : ni la saison, ni l\'heure, ni la lumière du jour à Bordeaux, alors que l\'aléatoire (SOMA) et les idle states (Perron) sont acceptés.',
        ] },
      ],
      bas: 'À Bordeaux, la barre est basse en design (un site plein cadre où un film joue suffirait à sortir du lot) mais haute en preuve (46 à 195 avis Google, logos nationaux). Un concept « dingue » ne doit donc jamais coûter la crédibilité : chaque concept ci-après garde le texte indexable, les chiffres et le contact à portée de pouce.',
    },
  ],
};

export const CONCEPTS = [
  {
    id: 'f1', num: '01', nom: 'Montage', famille: 'Le visiteur touche les rushes',
    phrase: 'Il n\'y a pas de showreel. Il y a un chutier, une timeline, et un film qui se monte sous vos yeux — puis sous vos doigts.',
    pitch: 'Le site est une table de montage vivante : à l\'arrivée, il monte lui-même un premier film à partir des rushes de tous vos projets, au rythme du visiteur. Puis le visiteur prend la main, glisse ses plans, et **envoie son montage avec sa demande de devis**. Le brief arrive déjà filmé.',
    pitchCourt: 'Le site est une table de montage : le film se monte au rythme du visiteur, qui peut reprendre la main et envoyer son montage avec sa demande.',
    dit: 'Un réalisateur qui montre sa matière, pas seulement son résultat. Qui fait confiance au client au point de lui laisser le chutier. Le plus généreux des trois.',
    rare: 'La Pac laisse choisir des films (« My Collection »), Ian Coad laisse explorer un reel. Personne ne laisse monter. Le corpus technique conclut : « aucun site primé de remix par le visiteur — territoire libre ».',
    etats: [
      'Arrivée : trois plans déjà posés, un quatrième en vol entre le chutier et la timeline ; la visionneuse joue le plan courant.',
      'Le visiteur prend la main : un plan en cours de glisser, marqueur d\'insertion terracotta, poignées de rognage, filtre Tourisme actif.',
      'Un film ouvert dans le chutier : sa bande de quatre photogrammes, client, catégorie, année, approche, « Ajouter ces rushes ».',
      'Contact : le montage du visiteur en bande (« 5 plans — 0:42 »), le formulaire court, « Envoyer avec ma demande ».',
    ],
    principe: [
      'Une maison de production choisit son showreel pour vous. Ici, le showreel est remplacé par sa matière première : un chutier de plans courts (6 à 10 secondes) tirés de tous vos films, chacun tagué par métier, lieu et lumière. Une timeline occupe le bas de l\'écran, une visionneuse le haut.',
      'À l\'arrivée, le site monte seul un premier film : les plans quittent le chutier un à un, se posent sur la timeline, la visionneuse enchaîne. Le rythme des coupes suit le visiteur : défilement ou pointeur lent, plans longs ; geste nerveux, coupes sèches. Chaque visite produit un film différent, et le visiteur le sent sans qu\'on le lui explique.',
      'Puis il prend la main. Un plan se glisse du chutier vers la timeline, se réordonne, se rogne par ses poignées. Les filtres par métier (Corporate, Événementiel, Immobilier, Tourisme, Clip) réduisent le chutier à ce qui le concerne : un promoteur monte en trente secondes une minute d\'immobilier.',
      'Le geste décisif est commercial : « Envoyer ce montage avec ma demande ». La liste des plans et leurs durées est jointe au formulaire. Vous recevez un brief qui est déjà une référence filmée : ce qu\'il a gardé, ce qu\'il a coupé, le rythme qu\'il aime. C\'est le trou « personne ne montre le processus » retourné en outil de vente.',
    ],
    parcours: [
      'Il arrive : le film se monte devant lui, la visionneuse joue. Il comprend en trois secondes qu\'il regarde un montage en train de se faire.',
      'Il bouge : le rythme change. Il ralentit, les plans s\'allongent. Le site répond.',
      'Il filtre « Immobilier » : le chutier se réduit à quatre films, la timeline se recompose.',
      'Il glisse un plan, en retire un autre. La visionneuse joue son montage. Il rogne une fin trop longue.',
      'Il ouvre un film du chutier : la fiche (client, année, approche, quatre photogrammes) et « Ajouter ces rushes ».',
      'Il va au contact : son montage est là, en bande. Il écrit trois lignes et envoie. Vous recevez le film et le message.',
    ],
    veille: [
      'Grille draggable à inertie (Phantom) et scrub encodé à images-clés courtes (KAI) : les deux briques techniques existent et sont documentées.',
      'Scrubber à vignettes de scènes (Önnu Jónu Son) : le modèle de la timeline lisible.',
      '« My Collection » (La Pac) prouve qu\'un professionnel accepte de composer sa sélection ; on va un cran plus loin.',
      'Contre-modèle assumé : pas d\'interface de logiciel de montage. Une table de montage sur papier crème, filets d\'encre, comme un dérushage.',
    ],
    archiLede: 'Pas de pages : tout se passe sur la table. Le menu (quatre mots, en haut à gauche) déplace la table plutôt que de changer d\'écran. Le montage du visiteur persiste d\'un état à l\'autre.',
    archi: [
      { k: 'Accueil', h: 'La table', d: 'Visionneuse, chutier filtré par métier, timeline. Le montage automatique puis manuel.' },
      { k: 'Films', h: 'Le chutier complet', d: 'Six bandes de rushes (quatre photogrammes chacune), client, catégorie, année, approche. « Ajouter ces rushes ».' },
      { k: 'Studio', h: 'Les marqueurs', d: 'Les trois partis pris du fondateur posés comme notes de montage sur la timeline ; son portrait dans la visionneuse.' },
      { k: 'Contact', h: 'L\'envoi', d: 'Le montage du visiteur en bande, un formulaire de quatre champs, « Envoyer avec ma demande ». Adresse, mail, téléphone toujours visibles.' },
      { k: 'Sans JS', h: 'Le repli', d: 'Une liste HTML complète des films (titre, client, lieu, année, durée) et la fiche de chaque film : indexable, lisible par les robots.' },
    ],
    gestes: [
      ['Arriver', 'Le premier montage se construit en 6 à 8 secondes ; un plan « en vol » toutes les 1,5 s.'],
      ['Bouger lentement / vite', 'La durée des plans suivants s\'ajuste (2 à 8 s). Le visiteur ne le lit nulle part : il le sent.'],
      ['Glisser du chutier', 'Curseur main fermée, marqueur d\'insertion terracotta, les plans s\'écartent pour faire place.'],
      ['Tirer une poignée', 'Rogne le plan ; la visionneuse saute au point rogné (jog).'],
      ['Filtrer un métier', 'Le chutier se réduit, la timeline se recompose sans vider ce que le visiteur a placé.'],
      ['Ouvrir un film', 'La bande se déplie en fiche ; « Ajouter ces rushes » pose ses quatre plans à la fin.'],
      ['Envoyer', 'Le montage (plans, durées, ordre) part avec le message, plus un lien pour le rejouer.'],
    ],
    motion: [
      'Le vol d\'un plan : courbe expo longue (900 ms), légère rotation, ombre portée sur le papier.',
      'Les coupes dans la visionneuse : franches, jamais de fondu ; c\'est un montage, pas un diaporama.',
      'La tête de lecture avance en continu ; le timecode en JetBrains Mono est le seul chiffre qui bouge.',
      'Quand le visiteur prend la main, le montage automatique s\'arrête sans à-coup : le plan « en vol » se pose et attend.',
      'Terracotta uniquement pour ce qui est sélectionné ou en cours : un seul élément chaud à la fois.',
    ],
    mobile: ['Visionneuse en haut, chutier en bande, timeline au pouce.', 'Appui long sur un plan : feuille « Ajouter au montage ».', 'Contact, avec la bande du montage.'],
    mobileTxt: 'Le glisser-déposer est remplacé par l\'appui long : « Ajouter au montage », « Retirer », « Rogner ». La timeline vit sous le pouce, au-dessus de la barre d\'accueil. Le montage automatique reste ; le rythme suit la vitesse de défilement. En réunion, un client monte 40 secondes d\'immobilier sur son téléphone et vous les envoie.',
    tech: [
      'Plans encodés courts (6 à 10 s), H.264 et AV1, images-clés toutes les 12 images pour un jog fluide (méthode KAI), affiche JPEG par plan.',
      'Visionneuse : une balise vidéo par plan, préchargement des deux suivants ; pas de WebGL nécessaire. Option : grain et coupe en shader sur un canvas.',
      'Timeline : DOM + pointer events, réordonnancement par calcul de positions ; inertie par ressort à pas fixe (déjà écrit dans le projet).',
      'Rythme : vitesse du pointeur et du défilement lissée sur 2 s → durée cible du plan suivant.',
      'État du montage dans l\'URL (liste d\'identifiants et durées) : partageable, rejouable, joint au formulaire.',
      'Repli : liste HTML des films et fiches statiques ; clavier : Tab sur les plans, Entrée pour ajouter, flèches pour déplacer.',
      'Poids cible à l\'arrivée : moins de 4 Mo, affiches d\'abord, vidéos ensuite.',
    ],
    besoin: '18 à 30 plans courts choisis dans vos rushes, tagués par métier et lieu. Une affiche par plan. Les six fiches existantes suffisent pour le reste.',
    risques: 'Un visiteur qui ne comprend pas qu\'il peut toucher : parade, le premier montage automatique et le plan « en vol » qui invite. Un montage envoyé sans message : parade, le montage est joint en plus du formulaire, pas à la place.',
    chiffres: [['6-8 sem.', 'fabrication'], ['≈ 25', 'plans à préparer'], ['0', 'WebGL requis']],
  },
  {
    id: 'f2', num: '02', nom: 'Le point', famille: 'La mise au point comme navigation',
    phrase: 'Un seul plan, avec de la profondeur. Ce qui est net se lit et se clique ; le reste attend, dans le flou, qu\'on tire le point.',
    pitch: 'Tout le site vit dans un seul plan à plusieurs distances : au premier plan les métiers et le contact, à trois mètres les films, à l\'infini le studio et Bordeaux. La navigation est la **bague de mise au point** : on tire le point du proche au lointain, et ce qui entre dans le net devient lisible.',
    pitchCourt: 'Il n\'y a pas de pages, il y a des distances : la bague de mise au point remplace le menu, ce qui est net se lit.',
    dit: 'Un réalisateur qui pense en profondeur de champ, qui choisit ce qu\'il rend net. Le plus sensuel des trois, et le plus proche d\'un geste d\'opérateur.',
    rare: 'Les cartes de profondeur servent au décor (Phantom, Scan Effect, particules 3D) ; le rack focus n\'est jamais un menu. Le corpus technique le propose comme extrapolation « B » sans exemple existant.',
    etats: [
      'Arrivée, point à l\'infini : le studio net au fond, les métiers énormes et flous devant, les films en bokeh au milieu ; la bague à droite.',
      'Point à trois mètres : les six films flottent, un seul net (« Gone Colors »), les autres se dissolvent selon leur distance.',
      'Dans un film : le point tiré à travers ses quatre plans, plan 2 net, l\'approche du réalisateur lisible, « Retour à la table ».',
      'Point à cinquante centimètres : les cinq métiers en grands mots nets, chacun avec sa phrase, la carte contact nette.',
    ],
    principe: [
      'Un opérateur ne montre pas tout à la fois : il choisit une distance et le reste s\'efface. Le site adopte ce principe comme structure. Il n\'y a pas de pages ; il y a des distances gravées sur une échelle de bague d\'objectif — 0,5 m, 1 m, 3 m, 10 m, ∞ — et à chaque instant une seule est nette.',
      'Le défilement, ou un glisser sur la bague à droite de l\'écran, tire le point. Ce qui entre dans le net devient lisible et cliquable ; ce qui en sort se dissout en bokeh chaud, crème et ambré, jamais noir. Le premier plan porte ce qui presse (les métiers, le contact) ; le milieu porte les films ; le fond porte le studio, le fondateur, Bordeaux.',
      'À trois mètres, les six films flottent à des profondeurs légèrement différentes. Affiner le point en choisit un ; l\'ouvrir fait de ses quatre photogrammes toute la pile de profondeur, et l\'on tire le point à travers le film, plan par plan. Le pointeur fait parallaxer les images : dans la version réelle, chaque photogramme porte une carte de profondeur estimée, et le flou dépend vraiment de la distance dans l\'image.',
      'Le site reste crème. C\'est la seule direction « immersive » du corpus qui n\'est pas noire : le flou de profondeur sur papier crème est une image qu\'aucun site de réalisateur ne donne.',
    ],
    parcours: [
      'Il arrive à l\'infini : le studio net, une phrase. Devant lui, des mots énormes et flous. Il comprend qu\'il y a quelque chose devant.',
      'Il fait défiler : le point vient vers lui. Les films se précisent, le fond se dissout.',
      'Il s\'arrête sur un film net ; les autres flottent. Il clique.',
      'Il tire le point à travers les quatre plans du film ; l\'approche du réalisateur se lit au passage.',
      'Il continue vers l\'avant : les métiers, énormes, puis le contact, à portée de main.',
      'Double-clic sur n\'importe quoi : le point se fait dessus. Tab : d\'une distance à l\'autre.',
    ],
    veille: [
      'Cartes de profondeur → parallaxe et balayage (Scan Effect, WebGPU) et portrait + profondeur → particules (Phantom) : la brique de profondeur par image existe.',
      'Flou de profondeur en deux passes (DoF sur FBO) documenté ; 4WIDE montre qu\'il faut le couper sur mobile, et comment.',
      '« Focus mode » à vitesse 0,6 (4WIDE) : le ralenti d\'entrée devient le signal « on entre dans le plan ».',
      'Contre-modèle : aucun preloader, aucun compteur. Le site est net dès la première image ; le flou arrive au premier geste.',
    ],
    archiLede: 'Cinq distances, une bague. Chaque distance est aussi une URL classique (/films, /metiers, /studio, /contact) pour les robots, les liens et le clavier ; la bague n\'est que la manière de s\'y rendre.',
    archi: [
      { k: '∞', h: 'Le fond', d: 'Le studio, la silhouette du fondateur, « Une histoire bien racontée ne s\'oublie pas. » et ses trois partis pris.' },
      { k: '10 m', h: 'Bordeaux', d: 'Les lieux tournés (Chartrons, Médoc, Bassin) avec les films qui s\'y rattachent : le territoire comme distance.' },
      { k: '3 m', h: 'Les films', d: 'Six films flottants à des profondeurs proches ; affiner choisit, ouvrir déploie les quatre plans en pile.' },
      { k: '1 m', h: 'Les métiers', d: 'Cinq mots énormes, chacun sa phrase ; le point sur l\'un d\'eux montre ses films derrière, flous.' },
      { k: '0,5 m', h: 'Le contact', d: 'Adresse, mail, téléphone, un formulaire de trois champs. Toujours la distance la plus proche, donc la plus rapide.' },
    ],
    gestes: [
      ['Défiler', 'Tire le point de loin vers près (ou l\'inverse), avec inertie ; l\'aiguille suit sur la bague.'],
      ['Glisser la bague', 'Réglage fin, comme une bague de suivi de point ; crans sur les cinq distances.'],
      ['Survoler un film net', 'Il ralentit (0,6×), les autres s\'écartent d\'un cran de flou.'],
      ['Cliquer un film', 'Ses quatre plans deviennent la pile ; l\'échelle affiche 1 · 2 · 3 · 4.'],
      ['Double-clic (ou double-tap)', 'Fait le point sur l\'élément visé, où qu\'il soit.'],
      ['Tab / flèches', 'Passe d\'une distance à l\'autre ; le contenu net reçoit le focus clavier.'],
      ['Bouger le pointeur', 'Parallaxe selon la profondeur de l\'image : le premier plan de la photo bouge plus que le fond.'],
    ],
    motion: [
      'Le tirage de point : 700 à 1 100 ms, courbe expo ; le flou et l\'échelle changent ensemble, jamais l\'un sans l\'autre.',
      'Le bokeh est chaud : le flou éclaircit et réchauffe (crème, ambre), il n\'assombrit jamais.',
      'L\'aiguille terracotta est le seul élément qui bouge en permanence ; tout le reste répond.',
      'Aucun fondu de page : la seule transition du site est optique.',
      'Au repos, une respiration de point très lente (±2 %) : le plan est vivant.',
    ],
    mobile: ['Infini : le fond net, la bague au pouce sur le bord droit.', 'Trois mètres : les films, un seul net, curseur au milieu.', 'Cinquante centimètres : métiers et contact nets.'],
    mobileTxt: 'La bague devient un curseur vertical sous le pouce droit, avec crans. Le défilement natif fait la même chose. Le flou lourd est remplacé par un flou léger sur images pré-floutées (trois niveaux par image, générés à la construction), comme 4WIDE coupe son flou sur mobile. Double-tap = faire le point. Le contact est toujours la distance la plus proche : deux crans depuis n\'importe où.',
    tech: [
      'Cartes de profondeur estimées une fois par image (modèle de profondeur monoculaire) et stockées en PNG 8 bits ; jamais calculées à la volée.',
      'Rendu WebGL : flou dépendant de la profondeur (deux passes), parallaxe UV ; repli CSS (filter: blur + échelle) sur les appareils sans WebGL ou en économie d\'énergie.',
      'Mobile : trois niveaux de flou pré-rendus par image, fondu croisé entre eux ; pas de post-process plein écran.',
      'Chaque distance = une route Next ; la bague met à jour l\'URL ; le rendu serveur livre le contenu net de la route demandée.',
      'Clavier : Tab parcourt les distances, le contenu flou est hors de l\'ordre de tabulation (inert).',
      'Respect de prefers-reduced-motion : tirage de point instantané, pas de respiration.',
      'Poids : une image nette + sa profondeur par plan ≈ 250 Ko ; l\'infini et les six films chargés d\'abord.',
    ],
    besoin: 'Une image forte par distance (le fond, Bordeaux) et les 24 photogrammes existants. Un lieu par film. Rien d\'autre.',
    risques: 'Le flou peut fatiguer : parade, le net occupe toujours plus de 40 % de l\'écran et le texte flou reste court. Le visiteur pressé : parade, le contact est à deux crans et un lien « Contact » classique reste en en-tête.',
    chiffres: [['7-9 sem.', 'fabrication'], ['24', 'cartes de profondeur'], ['WebGL', 'avec repli CSS']],
  },
  {
    id: 'f3', num: '03', nom: 'Découpage', famille: 'Le site écrit comme un réalisateur écrit',
    phrase: 'SÉQ. 01 — EXT. QUAI DES CHARTRONS — AUBE. Le site est le document de travail du réalisateur ; lire, c\'est naviguer.',
    pitch: 'Le site est un découpage technique : chaque film y est écrit plan par plan (valeur, mouvement, durée), et l\'image de chaque plan apparaît quand le regard passe sur sa ligne. Un appui maintenu **joue la séquence** comme un film. Les métiers, le studio et le contact sont les dernières séquences du même document.',
    pitchCourt: 'Le site est un découpage technique : chaque film écrit plan par plan, l\'image qui suit la lecture, la séquence qui se joue à l\'appui long.',
    dit: 'Un réalisateur qui pense avant de tourner, et qui le montre. Le plus « auteur » des trois, et le seul qui parle à la première personne — le trou n° 1 de la veille bordelaise.',
    rare: 'Aucun site du corpus ne montre un document de travail : ni découpage, ni note d\'intention. À Paris le silence, à Bordeaux la brochure. Et c\'est le seul concept 100 % texte, donc 100 % indexable — le contraire des sites primés (Igloo : sémantique 6,4/10).',
    etats: [
      'Arrivée : page 1 du découpage, SÉQ. 01, les premières lignes de plan, l\'image du plan 1 à droite avec son cartouche, « Maintenir pour lire ».',
      'Lecture : le regard sur le plan 3 de « The Sound of Discovery », ligne active en terracotta, note de marge du réalisateur.',
      '« Lecture » : appui maintenu, letterbox plein écran, le photogramme, la ligne du plan en sous-titre, timecode et progression.',
      'SÉQ. 10 — FIN : le contact écrit comme une page de scénario à remplir, « Envoyer le brief ».',
    ],
    principe: [
      'Avant de tourner, un réalisateur écrit : un découpage technique, séquence par séquence, plan par plan, avec la valeur (plan large, plan moyen, gros plan, insert), le mouvement (fixe, travelling, panoramique, à l\'épaule) et la durée. Ce document n\'est jamais montré aux clients. Le site le devient.',
      'La page d\'accueil s\'ouvre sur « SÉQ. 01 — EXT. QUAI DES CHARTRONS — AUBE » et se lit comme un scénario. Chaque ligne est un plan. Quand le regard (défilement, survol, tap) passe sur une ligne, la colonne de droite montre l\'image réelle de ce plan. Lire, c\'est naviguer ; il n\'y a pas de menu au sens habituel, il y a une table des séquences.',
      'Chacun des six films est une séquence, avec ses quatre plans et l\'approche du réalisateur en note de marge, à la première personne. Puis SÉQ. 08 « Ce que nous tournons » (les cinq métiers, écrits comme des plans), SÉQ. 09 « INT. STUDIO — JOUR » (le fondateur, ses trois partis pris) et SÉQ. 10 « FIN — Votre film commence ici » : le contact, en page de scénario à remplir (« VOTRE SÉQUENCE : INT./EXT. ____ — ____ »).',
      'Le geste supplémentaire est la lecture : un appui maintenu n\'importe où (ou la barre d\'espace) joue la séquence courante comme un film, en letterbox, avec les durées écrites dans le découpage, la ligne du plan en sous-titre et un timecode. Relâcher revient au document. Le papier et l\'écran, dans le même geste.',
    ],
    parcours: [
      'Il arrive sur une page de scénario. Il lit deux lignes ; l\'image change à droite. Il comprend le principe sans explication.',
      'Il descend dans « The Sound of Discovery » : quatre plans, une note de marge qui dit « je ».',
      'Il maintient le clic : la séquence se joue, letterbox, timecode. Il relâche : il est revenu à la ligne où il était.',
      'La table des séquences (en pied, ou touche T) l\'emmène à SÉQ. 08 : les métiers, un plan chacun.',
      'SÉQ. 09 : le fondateur, trois partis pris, le portrait à contre-jour.',
      'SÉQ. 10 : il remplit sa propre séquence (« EXT. DOMAINE — FIN DE JOURNÉE ») et envoie le brief.',
    ],
    veille: [
      'Le silence des maisons parisiennes et la brochure bordelaise laissent la voix du réalisateur vacante : la veille le note comme le trou n° 5 à Bordeaux.',
      'Letter to Memphis (trois études de cas racontées) et Henry de Czar (étapes datées) montrent que le récit de méthode convainc les clients corporate.',
      'Long press qui révèle la vidéo (David Whyte / Immersive Garden) et photogramme → film (extrapolation « F ») : la brique de la « lecture ».',
      'Bisous et Chems Studio prouvent qu\'un site de production tient sans WebGL, éditorial et rapide : c\'est la famille technique de Découpage.',
    ],
    archiLede: 'Un seul document, dix séquences, une table des séquences. Chaque séquence a son URL (/seq/03-the-shape-of-vastness) ; le découpage est une donnée structurée, donc un CMS, un flux et un PDF imprimable viennent gratuitement.',
    archi: [
      { k: 'SÉQ. 01', h: 'L\'ouverture', d: 'Quai des Chartrons, aube. Trois plans qui posent le lieu et le ton, le logotype, l\'indice « Maintenir pour lire ».' },
      { k: 'SÉQ. 02 → 07', h: 'Les six films', d: 'Quatre plans chacun (valeur, mouvement, durée, une ligne), client, année, note de marge à la première personne.' },
      { k: 'SÉQ. 08', h: 'Ce que nous tournons', d: 'Les cinq métiers écrits comme des plans, avec leur phrase. C\'est la page « services », sans en avoir l\'air.' },
      { k: 'SÉQ. 09', h: 'INT. STUDIO — JOUR', d: 'Le fondateur, ses trois partis pris, le portrait. Le « je » du site.' },
      { k: 'SÉQ. 10', h: 'FIN', d: '« Votre film commence ici » : la page de scénario à remplir, nom, société, message, « Envoyer le brief ». Adresse, mail, téléphone en pied.' },
    ],
    gestes: [
      ['Défiler', 'La ligne au tiers supérieur devient active ; l\'image de droite change en coupe franche.'],
      ['Survoler / taper une ligne', 'La rend active sans défiler ; la note de marge se déploie.'],
      ['Maintenir (ou Espace)', 'Joue la séquence courante en letterbox, avec les durées du découpage ; relâcher revient à la ligne.'],
      ['Touche T', 'Ouvre la table des séquences ; chiffres 1 à 0 pour sauter.'],
      ['Cliquer le cartouche', 'Ouvre le plan en grand, avec ses métadonnées (lieu, lumière, focale si connue).'],
      ['Imprimer', 'Le découpage sort en PDF propre, sans interface : le site est aussi un document.'],
      ['Remplir SÉQ. 10', 'Le brief part avec la séquence que le client a écrite lui-même.'],
    ],
    motion: [
      'Le changement d\'image est une coupe franche, jamais un fondu : on lit un découpage, on ne feuillette pas un album.',
      'La ligne active glisse en terracotta en 200 ms ; le numéro de plan se colore, rien d\'autre.',
      'La « lecture » descend un letterbox sombre en 400 ms, puis les plans s\'enchaînent aux durées écrites.',
      'Le curseur devient un petit « ▶ maintenir » sur le document, un « ✕ » pendant la lecture.',
      'Pas de défilement lissé : le papier a le défilement natif.',
    ],
    mobile: ['Le document défile, l\'image du plan courant collée en haut.', 'Une ligne tapée : active, image, note de marge déployée.', 'SÉQ. 10 : le contact en page de scénario.'],
    mobileTxt: 'Le document est déjà une colonne : il ne perd rien sur téléphone. L\'image du plan courant reste collée en haut (16:9), le cartouche compact dessous. L\'appui long joue la séquence en plein écran. C\'est le concept qui se lit le mieux en 30 secondes en réunion — le trou « mobile pour le client pressé » de la veille.',
    tech: [
      'Le découpage est une donnée : séquences → plans (valeur, mouvement, durée, ligne, image, vidéo). Un fichier JSON ou un CMS léger ; le rendu est serveur, HTML complet.',
      'La « lecture » utilise de vraies vidéos par plan (courtes, muettes ou non) quand elles existent, l\'image fixe sinon ; préchargement au premier survol.',
      'Aucune dépendance WebGL ; pointer events pour l\'appui maintenu, Intersection Observer pour la ligne active.',
      'SEO : chaque film est une page de texte structuré (titre, client, lieu, année, plans) ; données structurées VideoObject par plan.',
      'Accessibilité : le document est un vrai texte, navigable au clavier ; la lecture est annoncée ; contrastes encre sur crème vérifiés.',
      'Impression : feuille de style print qui sort le découpage en A4 propre.',
      'Poids : quelques dizaines de Ko de texte, les images à la demande ; le site le plus rapide des trois.',
    ],
    besoin: 'Écrire, ou faire écrire avec vous, le découpage réel de six films (quatre plans chacun) et une note d\'approche à la première personne. C\'est le seul concept dont la matière est d\'abord du texte.',
    risques: 'Trop de texte pour un client pressé : parade, les images changent à chaque ligne et la « lecture » donne le film en un geste. Un découpage inventé après coup peut sonner faux : parade, on part de vos vrais rushes et de vos vrais choix.',
    chiffres: [['4-6 sem.', 'fabrication'], ['≈ 40', 'lignes de plan à écrire'], ['100 %', 'indexable']],
  },
];

export const RECO = {
  titre: 'Trois concepts, un choix<span class="dot">.</span>',
  grille: [
    ['Effet « je n\'ai jamais vu ça »', 5, 5, 4],
    ['Geste de réalisateur', 4, 5, 5],
    ['Utile au client (brief, devis)', 5, 3, 4],
    ['Lecture en 30 s sur téléphone', 3, 3, 5],
    ['Indexable, crédible à Bordeaux', 3, 3, 5],
    ['Légèreté de fabrication', 3, 2, 5],
    ['Robustesse (vieillit bien)', 4, 3, 5],
  ],
  legende: 'Cinq carrés = le plus fort. Les notes sont un avis, pas une mesure : elles croisent la veille (ce qui est rare, ce qui vieillit mal) et ce que vos clients corporate, immobilier et tourisme attendent.',
  avis: [
    '**Montage** est le concept le plus « dingue » ET le plus utile : personne ne laisse le visiteur monter, et le montage envoyé avec la demande transforme un gadget en outil de vente. C\'est celui que je recommande si vous voulez un site dont on parle et qui rapporte des briefs meilleurs.',
    '**Le point** est le plus beau et le plus sensuel ; c\'est un geste d\'opérateur pur. Mais c\'est le plus coûteux, le plus fragile sur téléphone, et celui qui sert le moins directement le client. À choisir si l\'image de marque prime sur la conversion.',
    '**Découpage** est le plus sûr et le plus « auteur » : le seul qui parle à la première personne, le seul 100 % texte, le plus rapide à fabriquer et le seul qui gagne le référencement local face à Sajot, Fygo ou Biux. Il paraît moins spectaculaire en capture ; il l\'est en main, à cause de la lecture.',
  ],
  combine: 'Les trois se combinent : le découpage comme colonne vertébrale de chaque fiche film (texte, SEO, PDF), le montage comme accueil et comme outil de brief, la mise au point réservée à un seul moment (l\'ouverture d\'un film, ses quatre plans en pile). Mon assemblage préféré : **Montage + Découpage**, la mise au point en option plus tard.',
  suiteTitre: 'Comment on avance<span class="dot">.</span>',
  etapes: [
    { h: 'Choisir', d: 'Un concept, ou un assemblage. Dites ce qui vous a fait réagir dans les écrans, en bien comme en mal : c\'est ce qui guide la suite.' },
    { h: 'Préparer la matière', d: 'Montage : 25 plans courts tagués. Découpage : six découpages écrits avec vous. Le point : un lieu par film. Deux séances suffisent.' },
    { h: 'Construire', d: 'Version Next.js sur une branche, déployée en aperçu, testée sur iPhone réel et sur Safari. Le site actuel reste en ligne jusqu\'au dernier jour.' },
  ],
};
